name: CI Pipeline for 3 Tier NextJs Webapp


on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: chekout code
        uses: actions/checkout@v4
      - run: echo "code checkout successfully"
  test:
      runs-on: ubuntu-slim
      steps:
        - name: testing code 
          run: echo "testing phase"
  deploy:
        needs: 
          - build
          - test
        runs-on: ubuntu-slim
        steps:
          - name: deploy
            run: echo "deploy application"
