name: CI Pipeline for 3 Tier NextJs Webapp


on:
  workflow_dispatch:
  
jobs:
  
  build:
    environment: build
    runs-on: ubuntu-slim
    steps:
      - name: chekout code
        uses: actions/checkout@v4
      - run: echo "code checkout successfully with ${{vars.DB_NAME}}"
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.5.0
        with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 24

       # Install dependencies across all packages in the workspace
      - name: Install Workspace Dependencies
        run: |
          npm install
          ls -a
     
  
  
    
  staging:
        environment: staging
        runs-on: ubuntu-slim
        steps:
          - name: staging
            run: echo "staging step with ${{vars.DB_NAME}}"
            
  
  
  deploy:
        environment: deploy
        needs: 
          - build
        runs-on: ubuntu-slim
        steps:
          - name: deploy
            run: echo "deployment with ${{vars.DB_NAME}}"
          - name: deploy
            run: echo "deploy application"
