name: CI Pipeline for 3 Tier NextJs Webapp


on:
  push: 
    branches: ['main']
  pull_request:  
    branches: ['main']
  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-slim
     
    steps:
    - name: chekout code
      uses: actions/checkout@v4
    
    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'

    - name: install dependecies
      run: npm ci
      
    - name: test  
      run: echo "testing"

      
  build:
    environment: build
    runs-on: ubuntu-slim
    steps:
      - name: chekout code
        uses: actions/checkout@v4
      - run: echo "code checkout successfully with ${{vars.DB_NAME}}"
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v6.5.0
        with:
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
          node-version: 24

       # Install dependencies across all packages in the workspace
      - name: Install Workspace Dependencies
        run:  npm ci
      - name: run build  
        run: |
          npm run build:api
          npm run build:web
     
  
  

